### ISSUE TITLE
Support MSI for Storage Queues

### ISSUE THREAD

**Issue by rockanand** [rebus-org/Rebus.AzureQueues#12]
@mookid8000 @Tsjunne Is there a way to invoke MSI in ReBus?. (Queue Module)

service.addrebus(...
.transport(x => x.UseAzureStorageQueues(cloudstorageaccounnt (or) connection string ,"queuename",AzureStorageQueuesTransportOptions).

I'm trying to refer Managed Identity in Azure storage queues instead of storage account connection string (or) SAS.

Your assistance herein is greatly appreciated.

**Comment by mookid8000** [comment]
I've made some initial attempts at supporting managed identity in Rebus.AzureServiceBus.

Do you know how it's done with Azure Storage Queues?

**Comment by mookid8000** [comment]
hi @rockanand , I'm closing this one for now as I assume you found another way to make it work. Please don't hesitate to come back here if this is still something you're struggling with.
