### ISSUE TITLE
QueueServiceClient instead of IQueueClientFactory

### ISSUE THREAD

**Issue by SlowLogicBoy** [rebus-org/Rebus.AzureQueues#20]
Hey,

I'm curious is there a reason you are using your own [`IQueueClientFactory`](https://github.com/rebus-org/Rebus.AzureQueues/blob/master/Rebus.AzureQueues/AzureQueues/ConnectionStringQueueClientFactory.cs#L9) instead of `QueueServiceClient`?

**Comment by mookid8000** [comment]
Honestly, I don't know why and how the `IQueueClientFactory` came to be. I just took a git blame view, and it looks like it has my name on it, but I don't recall having introduced it.

It could have something to do with supporting multiple types of authentication (e.g. connection string credentials, managed identity, etc.), but I'm not sure.

Do you know if `QueueServiceClient` can fill this role?

**Comment by SlowLogicBoy** [comment]
As far as I can see it does the same thing as `IQueueClientFactory` I thought Rebus could reuse `QueueServiceClient` that I configure and register 🤔 and Rebus could to `TryAddSingleton` or w/e, but I guess it's not a big deal we just have multiple factories for same `QueueClient` 🤔

**Comment by mookid8000** [comment]
Ok! Let me know if you find out that there would be an advantage in switching over to `QueueServiceClient` 🙂
