### ISSUE TITLE
Package deprecation: WindowsAzure.Storage 

### ISSUE THREAD

**Issue by asleire** [rebus-org/Rebus.AzureQueues#5]
~~Microsoft has split the nuget package [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) into smaller more specialized packages (much like you did with Rebus.AzureStorage)~~

~~I believe this project should be updated to use the new package, [Microsoft.Azure.Storage.Queue](https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/), though it would be a breaking change.~~

~~Thoughts?~~

Just noticed you are actually using Microsoft.Azure.Storage.Queue, which is obviously the reason you split the project in the first place. The cause of my troubles is actually a breaking change made in Microsoft.Azure.Storage.Queue

**Comment by mookid8000** [comment]
👍 😁
